MODEL_NAME = "Qwen/Qwen2-VL-7B-Instruct"
EVALUATOR_MODEL_NAME = "gpt-oss-120b"
OUTPUT_DIR = "./qwen_grpo_robot"
DATASET_NAME = "DATASET_NAME = "reasoning-augmentation/reasoning_distractors_choice_deduped_templated""
DATASET_SPLIT = "train"
ALPHA = 0.5
BETA = 0.3
GAMMA = 0.2
NUM_EPOCHS = 1
BATCH_SIZE = 4
PER_DEVICE_TRAIN_BATCH_SIZE = 4
LEARNING_RATE = 1e-6
MAX_COMPLETION_LENGTH = 2048
NUM_GENERATIONS = 4
USE_VLLM = False
SAVE_STEPS = 2000
LOGGING_STEPS = 10
